name: CI Spring Boot API

# Run
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar o Java 21
        uses: actions/setup-java@v4
        with:
          # versão 21.
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Compilar o projeto
        run: mvn clean package -DskipTests